### ISSUE TITLE
Can not take screenshots from mathml pages

### ISSUE THREAD

**Issue by physikerwelt** [zeljkofilipin/screenshot-js#1]
If you call the program with

```
node screenshot.js https://en.wikipedia.org/api/rest_v1/media/math/render/mml/ab7894a9480a14798ca107181b7d9a34214303ff
```

no screenshot is taken and the following error is returned

```
/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^

WebDriverError: Could not take screenshot of current page - TypeError: d.style is undefined
    at WebDriverError (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/error.js:27:10)
    at Object.checkLegacyResponse (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/http/index.js:538:13)
    at /vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/http/index.js:472:11
    at ManagedPromise.invokeCallback_ (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/promise.js:2820:25
    at /vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.takeScreenshot()
    at Driver.schedule (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
    at Driver.takeScreenshot (/vagrant/srv/mathpipe/tools/screenshot-js/node_modules/selenium-webdriver/lib/webdriver.js:972:17)
    at Driver.webdriver.WebDriver.saveScreenshot (/vagrant/srv/mathpipe/tools/screenshot-js/screenshot.js:9:17)
    at Object.<anonymous> (/vagrant/srv/mathpipe/tools/screenshot-js/screenshot.js:17:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

@zeljkofilipin can you imagine a good place to report that issue.

cc @apsexton

**Comment by zeljkofilipin** [comment]
This is the correct place to report the issue. I took a quick look but could not find the solution. I am not sure when I will have the time to do more debugging. The strange thing is that I am getting a similar error when using ruby implementation too.

**Comment by physikerwelt** [comment]
I got the impression that this might be related
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7614

**Comment by zeljkofilipin** [comment]
Yes, looks like there is a problem with taking a screenshot of a page with no style. Can the mathml page be converted to html page, or embedded in a html page?

**Comment by zeljkofilipin** [comment]
I have a workaround that I managed to get working in Ruby, but I am having problems with rescuing exceptions in node :)

https://github.com/zeljkofilipin/screenshot-rb/commit/8692e238e495e1da68f185fb6b0e8620b3b95d0c

How do I rescue the exception in screenshot.js? I am reading https://nodejs.org/api/errors.html but whatever I try, the exception is never rescued.

**Comment by physikerwelt** [comment]
I have rewritten the node code to use promises
https://github.com/physikerwelt/mathpipe/blob/master/lib/pipes/firefox.js
This makes it easy to use catch https://github.com/physikerwelt/mathpipe/blob/master/lib/index.js#L116 to rescue the problem.
For me changing the extension from mml to html made the MathML come out nicely.

**Comment by zeljkofilipin** [comment]
How did you change mml to html?

**Comment by physikerwelt** [comment]
I basically copied the file contents to a new file with extension .html
https://github.com/physikerwelt/mathpipe/blob/master/lib/pipes/firefox.js#L25
I assumed that I would need to add header and footer. But apparently they were not needed and could stay empty.
